"""Add watch providers

Revision ID: 9ab06dc8405e
Revises: 6319dc194370
Create Date: 2026-09-02 14:15:53.848573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab06dc8405e'
down_revision: Union[str, None] = '6319dc194370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('watch_providers', sa.JSON(), nullable=True))
    op.add_column('content', sa.Column('providers_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'providers_synced_at')
    op.drop_column('content', 'watch_providers')
    # ### end Alembic commands ###
